name: fixture_factory
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/indipe-paytech/test-core"

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  recase: ^4.1.0


dev_dependencies:
  faker: ^2.1.0
  test: ^1.14.4
